openings_dataset_version: "2026-01-05"
chess_ext_version: "0.6.0"

# lumbrasgigabase last scan: 2026-03-03
sources:
  # Online datasets
  lumbras_online_1995_2009:
    mega: "gpoyCIxB#iYSuKRtJekGYzbJ6xGSA-LbSg6IXp9W0zM6Zrf_j9aE"
    category: "Online"
  lumbras_online_2010_2014:
    mega: "xlxHiABa#3by7ZAApVR2WIF1BdOI81Ld1sZLWoCjF1aQU42GH5VA"
    category: "Online"
  lumbras_online_2015_2019:
    mega: "N5h10ahK#9GeN1491qTBRXC-Sy3K7ex5g-zrsAoCtKS7DGVKCAHM"
    category: "Online"
  lumbras_online_2020:
    mega: "Eo4QjahT#9hfMIxqmCQVcQ9SvsyD6KyBDdjvOOLUlbM_v6VleT7M"
    category: "Online"
  lumbras_online_2021:
    mega: "kohSSLIA#fe77U0dT6kK3gTjAKangN1kyQJEIVyIjrogZ5YufWIA"
    category: "Online"
  lumbras_online_2022:
    mega: "tpZAEZBQ#xQ6Uj6E7SVaOcYOhNQ3uegeqd3pZWAKkOcKZXsru9As"
    category: "Online"
  lumbras_online_2023:
    mega: "Ish2zArD#LzmV9LqX7oWL3d6u-_C2v_4Ty1h6Ug1MajB7HelXDpA"
    category: "Online"
  lumbras_online_2024:
    mega: "V4ADSKDZ#d794fvofFuSZCo3-wnF5dxUfDJ5AOXjb0isFiE-wrKM"
    category: "Online"
  lumbras_online_2025:
    mega: "cxJBmbgJ#DVk7wBgq357ViguAwYcBthfJ1z6FdKU9IEQm5uwicTE"
    category: "Online"
  lumbras_online_2026_01:
    mega: "4ggwCTiY#b-i0yhoGOhgxJJWYrBq1EvOjhl4djAxDgCRWPMJemQQ"
    category: "Online"
  lumbras_online_2026_02:
    mega: "55gwHarS#CA5NSPjakoSwaAVclu8ioBv7JRkzQW8TZsCN92MfXOE"
    category: "Online"
  lumbras_online_2026_03:
    mega: "51wTyRDZ#Pf7kJDsua795R7SUD6M9FjkdsAh82kgIaSE5kvsV1Iw"
    category: "Online"

  # OTB datasets
  # lumbras_otb_nodate:
  #   mega: "ZpYgmA6Q#w3Edrxrh65XhDzFVYzvVjM8perZ-4viAw-QXLJF_Zjc"
  #   category: "OTB"
  lumbras_otb_0001_1899:
    mega: "99oQERJK#g65C4ljKy2UpQsVwF0Dz4641oCcpIBmDbVRMde6U2u0"
    category: "OTB"
  lumbras_otb_1900_1949:
    mega: "spo1jSRZ#X9mtcqQhQIRayEDFcUBzeMLydNGASUf_UMXRYXPs1vM"
    category: "OTB"
  lumbras_otb_1950_1969:
    mega: "5sY2xKwI#hQIMDGbZVR8rSpmUVl2NdaCYNcDhGeIWvb4s9BczYyg"
    category: "OTB"
  lumbras_otb_1970_1989:
    mega: "Bl5mXRBK#AP3Ut8984zPw8Kjt37j2UY6yGiE4zNAb_yd69iFs-fA"
    category: "OTB"
  lumbras_otb_1990_1999:
    mega: "dpRjWTYC#u5owPIrbxle15kTSfWQaHR-_cu6hEQNfhQyOvgRDd1Q"
    category: "OTB"
  lumbras_otb_2000_2004:
    mega: "I5ABlDKb#Hnntizohw8k3yWWLgN9dNyDXiVJSAEssD8qPYeG5tmw"
    category: "OTB"
  lumbras_otb_2005_2009:
    mega: "ptJ1VZCb#Cu8VbkM6Fej-qJzq947qyDkT8QVvi_ZCRRgD6V0mb3s"
    category: "OTB"
  lumbras_otb_2010_2014:
    mega: "looGTTgK#hh7G8H-etJnY-3ImHWJD6_lVa38mbTnt20VTtxASzUs"
    category: "OTB"
  lumbras_otb_2015_2019:
    mega: "Aw4VFDBS#tj--GMR1YMU-ayu67LmunymCXXDOS1tt9qxhmnbGYL4"
    category: "OTB"
  lumbras_otb_2020_2024:
    mega: "pxhGQKxA#14FxsF7xTW-LMouLSySTrMrCemyupQq5X-vSSOxeDkQ"
    category: "OTB"
  lumbras_otb_2025:
    mega: "Ulo0HCSb#wb6hi1p2YUH1BtXOj8aUOrTVQbQzcdgNQgeh8kSX31M"
    category: "OTB"
  lumbras_otb_2026_partial:
    mega: "spYwDSDA#hbSXrRR9Zwd98Tt-_HKF99SC28sWidrqw50goLIvPw0"
    category: "OTB"
